language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install r-base ash r-cran-rcpp

script:
  - pushd test && ./run_tests && popd

notifications:
  email:
    on_success: change
    on_failure: change

